// Regenerated by bin/build on every build. The committed values are
// placeholders so the package compiles on a fresh checkout — but anything
// surfaced through this file will read "unknown" unless bin/build is the
// build entry point. bin/run-shortcut-test runs bin/build automatically.
enum BuildInfo {
    static let gitSha: String = "unknown"
    static let gitDescribe: String = "unknown"
    static let buildDate: String = "unknown"

    static var versionString: String {
        "0.1.0 (\(gitDescribe))"
    }

    static var compiledByLine: String {
        "Compiled with perspective-cuts \(gitDescribe) on \(buildDate)"
    }
}
